/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.newyeti.common.avro.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Away extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8457361170421706107L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Away\",\"namespace\":\"com.newyeti.common.avro.schema\",\"fields\":[{\"name\":\"draw\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"goals\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Goals\",\"fields\":[{\"name\":\"against\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"for\",\"type\":[\"null\",\"int\"],\"default\":null}]}],\"default\":null},{\"name\":\"lose\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"played\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"win\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Away> ENCODER =
      new BinaryMessageEncoder<Away>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Away> DECODER =
      new BinaryMessageDecoder<Away>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Away> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Away> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Away>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Away to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Away from a ByteBuffer. */
  public static Away fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Integer draw;
  @Deprecated public com.newyeti.common.avro.schema.Goals goals;
  @Deprecated public java.lang.Integer lose;
  @Deprecated public java.lang.Integer played;
  @Deprecated public java.lang.Integer win;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Away() {}

  /**
   * All-args constructor.
   * @param draw The new value for draw
   * @param goals The new value for goals
   * @param lose The new value for lose
   * @param played The new value for played
   * @param win The new value for win
   */
  public Away(java.lang.Integer draw, com.newyeti.common.avro.schema.Goals goals, java.lang.Integer lose, java.lang.Integer played, java.lang.Integer win) {
    this.draw = draw;
    this.goals = goals;
    this.lose = lose;
    this.played = played;
    this.win = win;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return draw;
    case 1: return goals;
    case 2: return lose;
    case 3: return played;
    case 4: return win;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: draw = (java.lang.Integer)value$; break;
    case 1: goals = (com.newyeti.common.avro.schema.Goals)value$; break;
    case 2: lose = (java.lang.Integer)value$; break;
    case 3: played = (java.lang.Integer)value$; break;
    case 4: win = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'draw' field.
   * @return The value of the 'draw' field.
   */
  public java.lang.Integer getDraw() {
    return draw;
  }

  /**
   * Sets the value of the 'draw' field.
   * @param value the value to set.
   */
  public void setDraw(java.lang.Integer value) {
    this.draw = value;
  }

  /**
   * Gets the value of the 'goals' field.
   * @return The value of the 'goals' field.
   */
  public com.newyeti.common.avro.schema.Goals getGoals() {
    return goals;
  }

  /**
   * Sets the value of the 'goals' field.
   * @param value the value to set.
   */
  public void setGoals(com.newyeti.common.avro.schema.Goals value) {
    this.goals = value;
  }

  /**
   * Gets the value of the 'lose' field.
   * @return The value of the 'lose' field.
   */
  public java.lang.Integer getLose() {
    return lose;
  }

  /**
   * Sets the value of the 'lose' field.
   * @param value the value to set.
   */
  public void setLose(java.lang.Integer value) {
    this.lose = value;
  }

  /**
   * Gets the value of the 'played' field.
   * @return The value of the 'played' field.
   */
  public java.lang.Integer getPlayed() {
    return played;
  }

  /**
   * Sets the value of the 'played' field.
   * @param value the value to set.
   */
  public void setPlayed(java.lang.Integer value) {
    this.played = value;
  }

  /**
   * Gets the value of the 'win' field.
   * @return The value of the 'win' field.
   */
  public java.lang.Integer getWin() {
    return win;
  }

  /**
   * Sets the value of the 'win' field.
   * @param value the value to set.
   */
  public void setWin(java.lang.Integer value) {
    this.win = value;
  }

  /**
   * Creates a new Away RecordBuilder.
   * @return A new Away RecordBuilder
   */
  public static com.newyeti.common.avro.schema.Away.Builder newBuilder() {
    return new com.newyeti.common.avro.schema.Away.Builder();
  }

  /**
   * Creates a new Away RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Away RecordBuilder
   */
  public static com.newyeti.common.avro.schema.Away.Builder newBuilder(com.newyeti.common.avro.schema.Away.Builder other) {
    return new com.newyeti.common.avro.schema.Away.Builder(other);
  }

  /**
   * Creates a new Away RecordBuilder by copying an existing Away instance.
   * @param other The existing instance to copy.
   * @return A new Away RecordBuilder
   */
  public static com.newyeti.common.avro.schema.Away.Builder newBuilder(com.newyeti.common.avro.schema.Away other) {
    return new com.newyeti.common.avro.schema.Away.Builder(other);
  }

  /**
   * RecordBuilder for Away instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Away>
    implements org.apache.avro.data.RecordBuilder<Away> {

    private java.lang.Integer draw;
    private com.newyeti.common.avro.schema.Goals goals;
    private com.newyeti.common.avro.schema.Goals.Builder goalsBuilder;
    private java.lang.Integer lose;
    private java.lang.Integer played;
    private java.lang.Integer win;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.newyeti.common.avro.schema.Away.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.draw)) {
        this.draw = data().deepCopy(fields()[0].schema(), other.draw);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.goals)) {
        this.goals = data().deepCopy(fields()[1].schema(), other.goals);
        fieldSetFlags()[1] = true;
      }
      if (other.hasGoalsBuilder()) {
        this.goalsBuilder = com.newyeti.common.avro.schema.Goals.newBuilder(other.getGoalsBuilder());
      }
      if (isValidValue(fields()[2], other.lose)) {
        this.lose = data().deepCopy(fields()[2].schema(), other.lose);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.played)) {
        this.played = data().deepCopy(fields()[3].schema(), other.played);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.win)) {
        this.win = data().deepCopy(fields()[4].schema(), other.win);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Away instance
     * @param other The existing instance to copy.
     */
    private Builder(com.newyeti.common.avro.schema.Away other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.draw)) {
        this.draw = data().deepCopy(fields()[0].schema(), other.draw);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.goals)) {
        this.goals = data().deepCopy(fields()[1].schema(), other.goals);
        fieldSetFlags()[1] = true;
      }
      this.goalsBuilder = null;
      if (isValidValue(fields()[2], other.lose)) {
        this.lose = data().deepCopy(fields()[2].schema(), other.lose);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.played)) {
        this.played = data().deepCopy(fields()[3].schema(), other.played);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.win)) {
        this.win = data().deepCopy(fields()[4].schema(), other.win);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'draw' field.
      * @return The value.
      */
    public java.lang.Integer getDraw() {
      return draw;
    }

    /**
      * Sets the value of the 'draw' field.
      * @param value The value of 'draw'.
      * @return This builder.
      */
    public com.newyeti.common.avro.schema.Away.Builder setDraw(java.lang.Integer value) {
      validate(fields()[0], value);
      this.draw = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'draw' field has been set.
      * @return True if the 'draw' field has been set, false otherwise.
      */
    public boolean hasDraw() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'draw' field.
      * @return This builder.
      */
    public com.newyeti.common.avro.schema.Away.Builder clearDraw() {
      draw = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'goals' field.
      * @return The value.
      */
    public com.newyeti.common.avro.schema.Goals getGoals() {
      return goals;
    }

    /**
      * Sets the value of the 'goals' field.
      * @param value The value of 'goals'.
      * @return This builder.
      */
    public com.newyeti.common.avro.schema.Away.Builder setGoals(com.newyeti.common.avro.schema.Goals value) {
      validate(fields()[1], value);
      this.goalsBuilder = null;
      this.goals = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'goals' field has been set.
      * @return True if the 'goals' field has been set, false otherwise.
      */
    public boolean hasGoals() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'goals' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.newyeti.common.avro.schema.Goals.Builder getGoalsBuilder() {
      if (goalsBuilder == null) {
        if (hasGoals()) {
          setGoalsBuilder(com.newyeti.common.avro.schema.Goals.newBuilder(goals));
        } else {
          setGoalsBuilder(com.newyeti.common.avro.schema.Goals.newBuilder());
        }
      }
      return goalsBuilder;
    }

    /**
     * Sets the Builder instance for the 'goals' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.newyeti.common.avro.schema.Away.Builder setGoalsBuilder(com.newyeti.common.avro.schema.Goals.Builder value) {
      clearGoals();
      goalsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'goals' field has an active Builder instance
     * @return True if the 'goals' field has an active Builder instance
     */
    public boolean hasGoalsBuilder() {
      return goalsBuilder != null;
    }

    /**
      * Clears the value of the 'goals' field.
      * @return This builder.
      */
    public com.newyeti.common.avro.schema.Away.Builder clearGoals() {
      goals = null;
      goalsBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lose' field.
      * @return The value.
      */
    public java.lang.Integer getLose() {
      return lose;
    }

    /**
      * Sets the value of the 'lose' field.
      * @param value The value of 'lose'.
      * @return This builder.
      */
    public com.newyeti.common.avro.schema.Away.Builder setLose(java.lang.Integer value) {
      validate(fields()[2], value);
      this.lose = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lose' field has been set.
      * @return True if the 'lose' field has been set, false otherwise.
      */
    public boolean hasLose() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lose' field.
      * @return This builder.
      */
    public com.newyeti.common.avro.schema.Away.Builder clearLose() {
      lose = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'played' field.
      * @return The value.
      */
    public java.lang.Integer getPlayed() {
      return played;
    }

    /**
      * Sets the value of the 'played' field.
      * @param value The value of 'played'.
      * @return This builder.
      */
    public com.newyeti.common.avro.schema.Away.Builder setPlayed(java.lang.Integer value) {
      validate(fields()[3], value);
      this.played = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'played' field has been set.
      * @return True if the 'played' field has been set, false otherwise.
      */
    public boolean hasPlayed() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'played' field.
      * @return This builder.
      */
    public com.newyeti.common.avro.schema.Away.Builder clearPlayed() {
      played = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'win' field.
      * @return The value.
      */
    public java.lang.Integer getWin() {
      return win;
    }

    /**
      * Sets the value of the 'win' field.
      * @param value The value of 'win'.
      * @return This builder.
      */
    public com.newyeti.common.avro.schema.Away.Builder setWin(java.lang.Integer value) {
      validate(fields()[4], value);
      this.win = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'win' field has been set.
      * @return True if the 'win' field has been set, false otherwise.
      */
    public boolean hasWin() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'win' field.
      * @return This builder.
      */
    public com.newyeti.common.avro.schema.Away.Builder clearWin() {
      win = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Away build() {
      try {
        Away record = new Away();
        record.draw = fieldSetFlags()[0] ? this.draw : (java.lang.Integer) defaultValue(fields()[0]);
        if (goalsBuilder != null) {
          record.goals = this.goalsBuilder.build();
        } else {
          record.goals = fieldSetFlags()[1] ? this.goals : (com.newyeti.common.avro.schema.Goals) defaultValue(fields()[1]);
        }
        record.lose = fieldSetFlags()[2] ? this.lose : (java.lang.Integer) defaultValue(fields()[2]);
        record.played = fieldSetFlags()[3] ? this.played : (java.lang.Integer) defaultValue(fields()[3]);
        record.win = fieldSetFlags()[4] ? this.win : (java.lang.Integer) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Away>
    WRITER$ = (org.apache.avro.io.DatumWriter<Away>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Away>
    READER$ = (org.apache.avro.io.DatumReader<Away>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
