/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.newyeti.common.avro.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Goals extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3677822890221942351L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Goals\",\"namespace\":\"com.newyeti.common.avro.schema\",\"fields\":[{\"name\":\"against\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"for\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Goals> ENCODER =
      new BinaryMessageEncoder<Goals>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Goals> DECODER =
      new BinaryMessageDecoder<Goals>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Goals> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Goals> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Goals>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Goals to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Goals from a ByteBuffer. */
  public static Goals fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Integer against;
  @Deprecated public java.lang.Integer for$;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Goals() {}

  /**
   * All-args constructor.
   * @param against The new value for against
   * @param for$ The new value for for
   */
  public Goals(java.lang.Integer against, java.lang.Integer for$) {
    this.against = against;
    this.for$ = for$;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return against;
    case 1: return for$;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: against = (java.lang.Integer)value$; break;
    case 1: for$ = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'against' field.
   * @return The value of the 'against' field.
   */
  public java.lang.Integer getAgainst() {
    return against;
  }

  /**
   * Sets the value of the 'against' field.
   * @param value the value to set.
   */
  public void setAgainst(java.lang.Integer value) {
    this.against = value;
  }

  /**
   * Gets the value of the 'for$' field.
   * @return The value of the 'for$' field.
   */
  public java.lang.Integer getFor$() {
    return for$;
  }

  /**
   * Sets the value of the 'for$' field.
   * @param value the value to set.
   */
  public void setFor$(java.lang.Integer value) {
    this.for$ = value;
  }

  /**
   * Creates a new Goals RecordBuilder.
   * @return A new Goals RecordBuilder
   */
  public static com.newyeti.common.avro.schema.Goals.Builder newBuilder() {
    return new com.newyeti.common.avro.schema.Goals.Builder();
  }

  /**
   * Creates a new Goals RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Goals RecordBuilder
   */
  public static com.newyeti.common.avro.schema.Goals.Builder newBuilder(com.newyeti.common.avro.schema.Goals.Builder other) {
    return new com.newyeti.common.avro.schema.Goals.Builder(other);
  }

  /**
   * Creates a new Goals RecordBuilder by copying an existing Goals instance.
   * @param other The existing instance to copy.
   * @return A new Goals RecordBuilder
   */
  public static com.newyeti.common.avro.schema.Goals.Builder newBuilder(com.newyeti.common.avro.schema.Goals other) {
    return new com.newyeti.common.avro.schema.Goals.Builder(other);
  }

  /**
   * RecordBuilder for Goals instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Goals>
    implements org.apache.avro.data.RecordBuilder<Goals> {

    private java.lang.Integer against;
    private java.lang.Integer for$;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.newyeti.common.avro.schema.Goals.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.against)) {
        this.against = data().deepCopy(fields()[0].schema(), other.against);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.for$)) {
        this.for$ = data().deepCopy(fields()[1].schema(), other.for$);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Goals instance
     * @param other The existing instance to copy.
     */
    private Builder(com.newyeti.common.avro.schema.Goals other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.against)) {
        this.against = data().deepCopy(fields()[0].schema(), other.against);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.for$)) {
        this.for$ = data().deepCopy(fields()[1].schema(), other.for$);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'against' field.
      * @return The value.
      */
    public java.lang.Integer getAgainst() {
      return against;
    }

    /**
      * Sets the value of the 'against' field.
      * @param value The value of 'against'.
      * @return This builder.
      */
    public com.newyeti.common.avro.schema.Goals.Builder setAgainst(java.lang.Integer value) {
      validate(fields()[0], value);
      this.against = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'against' field has been set.
      * @return True if the 'against' field has been set, false otherwise.
      */
    public boolean hasAgainst() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'against' field.
      * @return This builder.
      */
    public com.newyeti.common.avro.schema.Goals.Builder clearAgainst() {
      against = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'for$' field.
      * @return The value.
      */
    public java.lang.Integer getFor$() {
      return for$;
    }

    /**
      * Sets the value of the 'for$' field.
      * @param value The value of 'for$'.
      * @return This builder.
      */
    public com.newyeti.common.avro.schema.Goals.Builder setFor$(java.lang.Integer value) {
      validate(fields()[1], value);
      this.for$ = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'for$' field has been set.
      * @return True if the 'for$' field has been set, false otherwise.
      */
    public boolean hasFor$() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'for$' field.
      * @return This builder.
      */
    public com.newyeti.common.avro.schema.Goals.Builder clearFor$() {
      for$ = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Goals build() {
      try {
        Goals record = new Goals();
        record.against = fieldSetFlags()[0] ? this.against : (java.lang.Integer) defaultValue(fields()[0]);
        record.for$ = fieldSetFlags()[1] ? this.for$ : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Goals>
    WRITER$ = (org.apache.avro.io.DatumWriter<Goals>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Goals>
    READER$ = (org.apache.avro.io.DatumReader<Goals>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
