receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: collector:5555
      http:
exporters:
  # prometheus:
  #   endpoint: collector:6666
  #   enable_open_metrics: true
  #   namespace: default
  logging:
    loglevel: info
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  # logging:
  #   loglevel: debug

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, otlp ]
    # metrics:
    #   receivers: [ otlp ]
    #   processors: [ batch ]
    #   exporters: [ prometheus ]