global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8181']
        labels:
          application: 'api-gateway'
  - job_name: 'beakon'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['beakon-service:4000']
        labels:
          application: 'beakon'
          
  