global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'apiscraper-producer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['apiscraper-producer-service:4000']
        labels:
          application: 'apiscraper-producer-service'
  - job_name: 'apiscraper-consumer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['apiscraper-consumer-service:4100']
        labels:
          application: 'apiscraper-producer-service'
