global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'beakon-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['beakon-service:4000']
        labels:
          application: 'beakon-service'
  - job_name: 'injester-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['injester-service:4100']
        labels:
          application: 'injester-service'
          
  