server:
  port: 4000

spring:
  application:
    name: BEAKON-SERVICE
  # config:
  #   import: "configserver:http://config-server:9091"
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

avro:
  topic:
    standings: "apiscraper.standings.avro.topic.v1"

football-api:
  baseUrl: "https://api-football-v1.p.rapidapi.com/v3"
  apiHost: "api-football-v1.p.rapidapi.com"
  apiKeys: 
    - "U4y3LniAIdmsh1SryySGibO7k8ELp1syFPvjsnpHOQNWAvpJAk"

app:
  kafka:
    send:
      enabled: false

---

spring:
  config:
    activate:
      on-profile:
      - dev
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
server:
  port: 7001

---

spring:
  config:
    import: configserver:http://config-server:9091
    activate:
      on-profile:
      - docker
  cloud:
    config:
        enabled: true
    discovery:
      enabled: true
  kafka:
    bootstrap-servers: broker-1:9092
    template:
      default-topic: "apiscraper.standings.avro.topic.v1"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: http://schema-registry:8081

app:
  kafka:
    send:
      enabled: true

# --- 

# spring:
#   config:
#     activate:
#       on-profile:
#       - test

# app:
#   kafka:
#     send:
#       enabled: true