server:
  port: 4000

spring:
  application:
    name: BEAKON-SERVICE
  # config:
  #   import: "configserver:http://config-server:9091"
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

avro:
  topic:
    standings: "apiscraper.standings.avro.topic.v1"

---

spring:
  config:
    activate:
      on-profile:
      - dev
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
server:
  port: 7001

---

spring:
  config:
    activate:
      on-profile:
      - docker
    import: "configserver:http://config-server:9091"
  kafka:
    bootstrap-servers: broker-1:9092
    template:
      default-topic: "apiscraper.standings.avro.topic.v1"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: http://schema-registry:8081